unit TestUnit1;
{
 Delphi DUnit Test Case
 ----------------------
 This unit contains a skeleton test case class generated by the Test Case Wizard.
 Modify the generated code to correctly setup and call the methods from the unit
 being tested.
}
interface
uses
 TestFramework, System.SysUtils, Vcl.Graphics, System.Generics.Collections,
 Vcl.StdCtrls, Winapi.Windows, System.Variants, System.Classes, Vcl.ComCtrls,
 Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages, Unit1;
type
 // Test methods for class TForm1
 TestTForm1 = class(TTestCase)
 strict private
 FForm1: TForm1;
 public
 procedure SetUp; override;
 procedure TearDown; override;
 published
 procedure TestCompare;
 end;
implementation
procedure TestTForm1.SetUp;
begin
 FForm1 := TForm1.Create;
end;
procedure TestTForm1.TearDown;
begin
 FForm1.Free;
 FForm1 := nil;
end;
procedure TestTForm1.TestCompare;
var
 ignoreCase: Boolean;
begin
 // TODO: Setup method call parameters
 FForm1.Compare(ignoreCase);
 // TODO: Validate method results
end;
initialization
 // Register any test cases with the test runner
 RegisterTest(TestTForm1.Suite);
end.
